// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqZb0dTyju_MRBPRhuoLPLYU_Ao7XTHo',
    appId: '1:932781822:web:61f873d500d300b6c94faf',
    messagingSenderId: '932781822',
    projectId: 'instagram-clone-b1cfc',
    authDomain: 'instagram-clone-b1cfc.firebaseapp.com',
    storageBucket: 'instagram-clone-b1cfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-55S4u5qAmcsiBk-x_MapQB6d5qEskYc',
    appId: '1:932781822:android:c21e895573082e48c94faf',
    messagingSenderId: '932781822',
    projectId: 'instagram-clone-b1cfc',
    storageBucket: 'instagram-clone-b1cfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCL_8ysQpaKniMS7be286aRFB3VGsQNCg',
    appId: '1:932781822:ios:f4220ee106515972c94faf',
    messagingSenderId: '932781822',
    projectId: 'instagram-clone-b1cfc',
    storageBucket: 'instagram-clone-b1cfc.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCL_8ysQpaKniMS7be286aRFB3VGsQNCg',
    appId: '1:932781822:ios:3cf8576234e40922c94faf',
    messagingSenderId: '932781822',
    projectId: 'instagram-clone-b1cfc',
    storageBucket: 'instagram-clone-b1cfc.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
